<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LHVOOHO" failures="1" tests="10" name="numpyninja.Tests.HomeTest" time="4.575" errors="0" timestamp="2022-09-27T14:23:03 EDT" skipped="0">
  <testcase classname="numpyninja.Tests.HomeTest" name="dropdownclick" time="0.605"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="DSgetstarted" time="0.420">
    <failure message="expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/data-structures-introduction/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/data-structures-introduction/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at numpyninja.Tests.HomeTest.DSgetstarted(HomeTest.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DSgetstarted -->
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="Arraygetstarted" time="0.312"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="linkedListgetstarted" time="0.432"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="stackGetstarted" time="0.584"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="queueGetstarted" time="0.425"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="treeGetstarted" time="0.462"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="graphGetstarted" time="0.456"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="SigninValidation" time="0.551"/>
  <system-out/>
  <testcase classname="numpyninja.Tests.HomeTest" name="RegisterValidation" time="0.328"/>
  <system-out/>
</testsuite> <!-- numpyninja.Tests.HomeTest -->
